// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATcpzn5laKXGbGrb7ZYhuyKP9eS8HRRrY',
    appId: '1:501057036787:web:3043fd5925d0d5466ef286',
    messagingSenderId: '501057036787',
    projectId: 'flutterappm2tl',
    authDomain: 'flutterappm2tl.firebaseapp.com',
    storageBucket: 'flutterappm2tl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaQsUW8uISXAJCulpFO-dyvfKuCFUiunY',
    appId: '1:501057036787:android:ab945c84fd7d6e6e6ef286',
    messagingSenderId: '501057036787',
    projectId: 'flutterappm2tl',
    storageBucket: 'flutterappm2tl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH7aoQOHdeLtXXwLFHxmPfc2yjX_UO35w',
    appId: '1:501057036787:ios:f74b25ea38155a606ef286',
    messagingSenderId: '501057036787',
    projectId: 'flutterappm2tl',
    storageBucket: 'flutterappm2tl.appspot.com',
    iosClientId: '501057036787-br7cqgbjdjg8ugpje8p4qcnmi4kip873.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH7aoQOHdeLtXXwLFHxmPfc2yjX_UO35w',
    appId: '1:501057036787:ios:f74b25ea38155a606ef286',
    messagingSenderId: '501057036787',
    projectId: 'flutterappm2tl',
    storageBucket: 'flutterappm2tl.appspot.com',
    iosClientId: '501057036787-br7cqgbjdjg8ugpje8p4qcnmi4kip873.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
